/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Block from './Block';

/**
 * The AddBlockErrorResponse model module.
 * @module model/AddBlockErrorResponse
 * @version 1.3.1
 */
class AddBlockErrorResponse {
    /**
     * Constructs a new <code>AddBlockErrorResponse</code>.
     * The error response schema for failed block adding
     * @alias module:model/AddBlockErrorResponse
     */
    constructor() { 
        
        AddBlockErrorResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddBlockErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddBlockErrorResponse} obj Optional instance to populate.
     * @return {module:model/AddBlockErrorResponse} The populated <code>AddBlockErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddBlockErrorResponse();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('block')) {
                obj['block'] = Block.constructFromObject(data['block']);
            }
            if (data.hasOwnProperty('lastBlock')) {
                obj['lastBlock'] = Block.constructFromObject(data['lastBlock']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AddBlockErrorResponse.CodeEnum} code
 */
AddBlockErrorResponse.prototype['code'] = undefined;

/**
 * @member {String} message
 */
AddBlockErrorResponse.prototype['message'] = undefined;

/**
 * @member {module:model/Block} block
 */
AddBlockErrorResponse.prototype['block'] = undefined;

/**
 * @member {module:model/Block} lastBlock
 */
AddBlockErrorResponse.prototype['lastBlock'] = undefined;





/**
 * Allowed values for the <code>code</code> property.
 * @enum {String}
 * @readonly
 */
AddBlockErrorResponse['CodeEnum'] = {

    /**
     * value: "BlockIsNotValidError"
     * @const
     */
    "BlockIsNotValidError": "BlockIsNotValidError"
};



export default AddBlockErrorResponse;

