/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pokemoncard from './Pokemoncard';

/**
 * The BuyDefaultPackageSchemaResponse model module.
 * @module model/BuyDefaultPackageSchemaResponse
 * @version 1.4.0
 */
class BuyDefaultPackageSchemaResponse {
    /**
     * Constructs a new <code>BuyDefaultPackageSchemaResponse</code>.
     * Buy a default cardpackage and receive an array of bought cards
     * @alias module:model/BuyDefaultPackageSchemaResponse
     */
    constructor() { 
        
        BuyDefaultPackageSchemaResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BuyDefaultPackageSchemaResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BuyDefaultPackageSchemaResponse} obj Optional instance to populate.
     * @return {module:model/BuyDefaultPackageSchemaResponse} The populated <code>BuyDefaultPackageSchemaResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BuyDefaultPackageSchemaResponse();

            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], [Pokemoncard]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Pokemoncard>} cards
 */
BuyDefaultPackageSchemaResponse.prototype['cards'] = undefined;






export default BuyDefaultPackageSchemaResponse;

