/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pokemoncard from './Pokemoncard';

/**
 * The CardPack model module.
 * @module model/CardPack
 * @version 1.3.1
 */
class CardPack {
    /**
     * Constructs a new <code>CardPack</code>.
     * A pack of cards. Formerly known as Booster.
     * @alias module:model/CardPack
     * @param name {String} 
     * @param cards {Array.<module:model/Pokemoncard>} 
     */
    constructor(name, cards) { 
        
        CardPack.initialize(this, name, cards);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, cards) { 
        obj['name'] = name;
        obj['cards'] = cards;
    }

    /**
     * Constructs a <code>CardPack</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardPack} obj Optional instance to populate.
     * @return {module:model/CardPack} The populated <code>CardPack</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardPack();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], [Pokemoncard]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CardPack.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/Pokemoncard>} cards
 */
CardPack.prototype['cards'] = undefined;






export default CardPack;

