/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pokemoncard from './Pokemoncard';

/**
 * The CardsResponse model module.
 * @module model/CardsResponse
 * @version 1.4.0
 */
class CardsResponse {
    /**
     * Constructs a new <code>CardsResponse</code>.
     * Returns an array of cards
     * @alias module:model/CardsResponse
     * @param cards {Array.<module:model/Pokemoncard>} 
     */
    constructor(cards) { 
        
        CardsResponse.initialize(this, cards);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cards) { 
        obj['cards'] = cards;
    }

    /**
     * Constructs a <code>CardsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardsResponse} obj Optional instance to populate.
     * @return {module:model/CardsResponse} The populated <code>CardsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardsResponse();

            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], [Pokemoncard]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Pokemoncard>} cards
 */
CardsResponse.prototype['cards'] = undefined;






export default CardsResponse;

