/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TheAbilitySchema from './TheAbilitySchema';
import TheItemsSchema from './TheItemsSchema';
import TheItemsSchema1 from './TheItemsSchema1';

/**
 * The Pokemoncard model module.
 * @module model/Pokemoncard
 * @version 1.3.1
 */
class Pokemoncard {
    /**
     * Constructs a new <code>Pokemoncard</code>.
     * A Pokemon card
     * @alias module:model/Pokemoncard
     * @param id {String} 
     * @param name {String} 
     */
    constructor(id, name) { 
        
        Pokemoncard.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Pokemoncard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Pokemoncard} obj Optional instance to populate.
     * @return {module:model/Pokemoncard} The populated <code>Pokemoncard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pokemoncard();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('subtype')) {
                obj['subtype'] = ApiClient.convertToType(data['subtype'], 'String');
            }
            if (data.hasOwnProperty('supertype')) {
                obj['supertype'] = ApiClient.convertToType(data['supertype'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'String');
            }
            if (data.hasOwnProperty('artist')) {
                obj['artist'] = ApiClient.convertToType(data['artist'], 'String');
            }
            if (data.hasOwnProperty('rarity')) {
                obj['rarity'] = ApiClient.convertToType(data['rarity'], 'String');
            }
            if (data.hasOwnProperty('series')) {
                obj['series'] = ApiClient.convertToType(data['series'], 'String');
            }
            if (data.hasOwnProperty('set')) {
                obj['set'] = ApiClient.convertToType(data['set'], 'String');
            }
            if (data.hasOwnProperty('setCode')) {
                obj['setCode'] = ApiClient.convertToType(data['setCode'], 'String');
            }
            if (data.hasOwnProperty('imageUrlHiRes')) {
                obj['imageUrlHiRes'] = ApiClient.convertToType(data['imageUrlHiRes'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], ['String']);
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('evolvesFrom')) {
                obj['evolvesFrom'] = ApiClient.convertToType(data['evolvesFrom'], 'String');
            }
            if (data.hasOwnProperty('ability')) {
                obj['ability'] = TheAbilitySchema.constructFromObject(data['ability']);
            }
            if (data.hasOwnProperty('hp')) {
                obj['hp'] = ApiClient.convertToType(data['hp'], 'String');
            }
            if (data.hasOwnProperty('retreatCost')) {
                obj['retreatCost'] = ApiClient.convertToType(data['retreatCost'], ['String']);
            }
            if (data.hasOwnProperty('convertedRetreatCost')) {
                obj['convertedRetreatCost'] = ApiClient.convertToType(data['convertedRetreatCost'], 'Number');
            }
            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], ['String']);
            }
            if (data.hasOwnProperty('attacks')) {
                obj['attacks'] = ApiClient.convertToType(data['attacks'], [TheItemsSchema]);
            }
            if (data.hasOwnProperty('weaknesses')) {
                obj['weaknesses'] = ApiClient.convertToType(data['weaknesses'], [TheItemsSchema1]);
            }
            if (data.hasOwnProperty('nationalPokedexNumber')) {
                obj['nationalPokedexNumber'] = ApiClient.convertToType(data['nationalPokedexNumber'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Pokemoncard.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Pokemoncard.prototype['name'] = undefined;

/**
 * @member {String} imageUrl
 */
Pokemoncard.prototype['imageUrl'] = undefined;

/**
 * @member {String} subtype
 */
Pokemoncard.prototype['subtype'] = undefined;

/**
 * @member {String} supertype
 */
Pokemoncard.prototype['supertype'] = undefined;

/**
 * @member {String} number
 */
Pokemoncard.prototype['number'] = undefined;

/**
 * @member {String} artist
 */
Pokemoncard.prototype['artist'] = undefined;

/**
 * @member {String} rarity
 * @default ''
 */
Pokemoncard.prototype['rarity'] = '';

/**
 * @member {String} series
 */
Pokemoncard.prototype['series'] = undefined;

/**
 * @member {String} set
 */
Pokemoncard.prototype['set'] = undefined;

/**
 * @member {String} setCode
 */
Pokemoncard.prototype['setCode'] = undefined;

/**
 * @member {String} imageUrlHiRes
 */
Pokemoncard.prototype['imageUrlHiRes'] = undefined;

/**
 * @member {Array.<String>} text
 */
Pokemoncard.prototype['text'] = undefined;

/**
 * @member {String} level
 */
Pokemoncard.prototype['level'] = undefined;

/**
 * @member {String} evolvesFrom
 */
Pokemoncard.prototype['evolvesFrom'] = undefined;

/**
 * @member {module:model/TheAbilitySchema} ability
 */
Pokemoncard.prototype['ability'] = undefined;

/**
 * @member {String} hp
 */
Pokemoncard.prototype['hp'] = undefined;

/**
 * @member {Array.<String>} retreatCost
 */
Pokemoncard.prototype['retreatCost'] = undefined;

/**
 * @member {Number} convertedRetreatCost
 */
Pokemoncard.prototype['convertedRetreatCost'] = undefined;

/**
 * @member {Array.<String>} types
 */
Pokemoncard.prototype['types'] = undefined;

/**
 * @member {Array.<module:model/TheItemsSchema>} attacks
 */
Pokemoncard.prototype['attacks'] = undefined;

/**
 * @member {Array.<module:model/TheItemsSchema1>} weaknesses
 */
Pokemoncard.prototype['weaknesses'] = undefined;

/**
 * @member {Number} nationalPokedexNumber
 */
Pokemoncard.prototype['nationalPokedexNumber'] = undefined;






export default Pokemoncard;

