/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisterErrorResponse model module.
 * @module model/RegisterErrorResponse
 * @version 1.3.1
 */
class RegisterErrorResponse {
    /**
     * Constructs a new <code>RegisterErrorResponse</code>.
     * The error when register failed
     * @alias module:model/RegisterErrorResponse
     */
    constructor() { 
        
        RegisterErrorResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegisterErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterErrorResponse} obj Optional instance to populate.
     * @return {module:model/RegisterErrorResponse} The populated <code>RegisterErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterErrorResponse();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RegisterErrorResponse.CodeEnum} code
 */
RegisterErrorResponse.prototype['code'] = undefined;

/**
 * @member {String} message
 */
RegisterErrorResponse.prototype['message'] = undefined;

/**
 * @member {String} username
 */
RegisterErrorResponse.prototype['username'] = undefined;





/**
 * Allowed values for the <code>code</code> property.
 * @enum {String}
 * @readonly
 */
RegisterErrorResponse['CodeEnum'] = {

    /**
     * value: "UserAlreadyExists"
     * @const
     */
    "UserAlreadyExists": "UserAlreadyExists"
};



export default RegisterErrorResponse;

