/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TheItemsSchema model module.
 * @module model/TheItemsSchema
 * @version 1.3.1
 */
class TheItemsSchema {
    /**
     * Constructs a new <code>TheItemsSchema</code>.
     * @alias module:model/TheItemsSchema
     * @param name {String} 
     * @param cost {Array.<String>} 
     * @param convertedEnergyCost {Number} 
     * @param damage {String} 
     */
    constructor(name, cost, convertedEnergyCost, damage) { 
        
        TheItemsSchema.initialize(this, name, cost, convertedEnergyCost, damage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, cost, convertedEnergyCost, damage) { 
        obj['name'] = name;
        obj['cost'] = cost;
        obj['convertedEnergyCost'] = convertedEnergyCost;
        obj['damage'] = damage;
    }

    /**
     * Constructs a <code>TheItemsSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TheItemsSchema} obj Optional instance to populate.
     * @return {module:model/TheItemsSchema} The populated <code>TheItemsSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TheItemsSchema();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cost')) {
                obj['cost'] = ApiClient.convertToType(data['cost'], ['String']);
            }
            if (data.hasOwnProperty('convertedEnergyCost')) {
                obj['convertedEnergyCost'] = ApiClient.convertToType(data['convertedEnergyCost'], 'Number');
            }
            if (data.hasOwnProperty('damage')) {
                obj['damage'] = ApiClient.convertToType(data['damage'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 * @default ''
 */
TheItemsSchema.prototype['name'] = '';

/**
 * @member {Array.<String>} cost
 */
TheItemsSchema.prototype['cost'] = undefined;

/**
 * @member {Number} convertedEnergyCost
 * @default 0
 */
TheItemsSchema.prototype['convertedEnergyCost'] = 0;

/**
 * @member {String} damage
 */
TheItemsSchema.prototype['damage'] = undefined;

/**
 * @member {String} text
 */
TheItemsSchema.prototype['text'] = undefined;






export default TheItemsSchema;

