/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TheItemsSchema1 model module.
 * @module model/TheItemsSchema1
 * @version 1.3.1
 */
class TheItemsSchema1 {
    /**
     * Constructs a new <code>TheItemsSchema1</code>.
     * @alias module:model/TheItemsSchema1
     * @param type {String} 
     * @param value {String} 
     */
    constructor(type, value) { 
        
        TheItemsSchema1.initialize(this, type, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, value) { 
        obj['type'] = type;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>TheItemsSchema1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TheItemsSchema1} obj Optional instance to populate.
     * @return {module:model/TheItemsSchema1} The populated <code>TheItemsSchema1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TheItemsSchema1();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
TheItemsSchema1.prototype['type'] = undefined;

/**
 * @member {String} value
 */
TheItemsSchema1.prototype['value'] = undefined;






export default TheItemsSchema1;

