/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UnauthorizedError model module.
 * @module model/UnauthorizedError
 * @version 1.4.0
 */
class UnauthorizedError {
    /**
     * Constructs a new <code>UnauthorizedError</code>.
     * Unauthorized Request
     * @alias module:model/UnauthorizedError
     */
    constructor() { 
        
        UnauthorizedError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UnauthorizedError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UnauthorizedError} obj Optional instance to populate.
     * @return {module:model/UnauthorizedError} The populated <code>UnauthorizedError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnauthorizedError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UnauthorizedError.CodeEnum} code
 */
UnauthorizedError.prototype['code'] = undefined;

/**
 * @member {String} message
 */
UnauthorizedError.prototype['message'] = undefined;





/**
 * Allowed values for the <code>code</code> property.
 * @enum {String}
 * @readonly
 */
UnauthorizedError['CodeEnum'] = {

    /**
     * value: "UnauthorizedError"
     * @const
     */
    "UnauthorizedError": "UnauthorizedError"
};



export default UnauthorizedError;

