/**
 * Pokecoin
 * The Pokecoin documentation
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangePasswordBody model module.
 * @module model/ChangePasswordBody
 * @version 1.4.0
 */
class ChangePasswordBody {
    /**
     * Constructs a new <code>ChangePasswordBody</code>.
     * @alias module:model/ChangePasswordBody
     * @param password {String} 
     * @param newPassword {String} 
     */
    constructor(password, newPassword) { 
        
        ChangePasswordBody.initialize(this, password, newPassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password, newPassword) { 
        obj['password'] = password;
        obj['newPassword'] = newPassword;
    }

    /**
     * Constructs a <code>ChangePasswordBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangePasswordBody} obj Optional instance to populate.
     * @return {module:model/ChangePasswordBody} The populated <code>ChangePasswordBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangePasswordBody();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('newPassword')) {
                obj['newPassword'] = ApiClient.convertToType(data['newPassword'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} password
 */
ChangePasswordBody.prototype['password'] = undefined;

/**
 * @member {String} newPassword
 */
ChangePasswordBody.prototype['newPassword'] = undefined;






export default ChangePasswordBody;

